services:
    app:
        image: ghcr.io/thanhnam2811/tiny-link:latest
        container_name: tiny-link-app
        ports:
            - '3001:3001'
        env_file:
            - packages/server/.env.production
        environment:
            NODE_ENV: production
            PORT: 3001
        restart: unless-stopped
        healthcheck:
            test: ['CMD-SHELL', 'wget -q -O - http://localhost:3001/api/healthz || exit 1']
            interval: 10s
            timeout: 3s
            retries: 5
            start_period: 20s
