packages:
  - packages/*

injectWorkspacePackages: true

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - argon2
  - esbuild
  - msw
  - prisma
  - sharp
  - unrs-resolver

syncInjectedDepsAfterScripts:
  - build
