export const SYSTEM_CONFIG = {
	REDIS_CACHE_TTL_SECONDS: 86400, // 24 hours
	REDIS_NOT_FOUND_TTL_SECONDS: 180, // 3 minutes
	SHORT_LINK_LENGTH: 7,
	SHORT_LINK_MAX_RETRIES: 3,
	PAGINATION_LIMIT: 10,
	RATE_LIMIT_GLOBAL: 100,
	RATE_LIMIT_CREATE_LINK: 10,
	RATE_LIMIT_VERIFY_PASSWORD: 5,
	RATE_LIMIT_WINDOW: '1 minute',
} as const;

export const ENV_NAMES = {
	TEST: 'test',
	DEVELOPMENT: 'development',
	PRODUCTION: 'production',
} as const;

export const HTTP_STATUS = {
	OK: 200,
	CREATED: 201,
	BAD_REQUEST: 400,
	UNAUTHORIZED: 401,
	FORBIDDEN: 403,
	NOT_FOUND: 404,
	CONFLICT: 409,
	GONE: 410,
	UNPROCESSABLE_ENTITY: 422,
	TOO_MANY_REQUESTS: 429,
	INTERNAL_SERVER_ERROR: 500,
} as const;

export const ERROR_MESSAGES = {
	LINK_NOT_FOUND: 'LINK_NOT_FOUND',
	LINK_GONE: 'LINK_GONE',
	LINK_EXPIRED: 'LINK_EXPIRED',
	LINK_UNAUTHORIZED: 'LINK_UNAUTHORIZED',
	LINK_CODE_CONFLICT: 'LINK_CODE_CONFLICT',
	INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
	VALIDATION_ERROR: 'VALIDATION_ERROR',
	ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
	RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
} as const;
